#spring:
#  datasource:
#    username: root 
#    password: Img_19062006
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/testdb?autoReconnect=true&useSSL=false

spring:  h2:    console:      enabled: true  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:     url: jdbc:h2:mem:test
  jpa:    generate-ddl: true
    hibernate:      ddl-auto: create-drop
    show-sql: true
  
logging:  level:    '[org.springframework.data]': INFO
    